### ISSUE TITLE
Doubt about league

### ISSUE THREAD

**Issue by mattnicee7** [Lycoon/clash-api#1]
I'm using your API to make a discord bot and I went to make a command to get informations of a league group, but when I put a tag of my clan to see my group, everything is null except the clan names, it could help me?

![null](https://user-images.githubusercontent.com/81203753/144968837-c53c653d-e5bd-40b9-ad35-44e10313efbb.png)

**Comment by mattnicee7** [comment]
![image](https://user-images.githubusercontent.com/81203753/144968872-0811b684-a2cd-4a47-b599-8d11ca0614c1.png)

**Comment by Lycoon** [comment]
Hi @mattnicee7

Unfortunately, Clash of Clans API does not provide such data as stars, attacks or destruction percentage for individual clans returned by this route. Models for ClashAPI will all be updated soon to be more consistent and generic as of now the fields you were using were not even `@Nullable` in my code.

What you need to do is to fetch individual clan warleagues results with other calls on `.getCWLWar(warTag)` where warTag is given with `.getRounds()[i].getWarsTags()[i]` on your leagueGroup here. I've done that with my bot that's using this API.

You can check [here](https://github.com/Lycoon/clashbot/blob/532af34001d5c4a4709b6749617ce9d2ad226060/src/main/java/com/lycoon/clashbot/commands/clan/WarLeagueCommand.java#L52) to see how it's done.

If you have any other related questions, don't mind answering to this issue! 😊

**Comment by mattnicee7** [comment]
Thanks so much @Lycoon <3
